[tool.poetry]
name = "uscis"
version = "0.1.0"
description = ""
authors = ["Bence Nagy <nagy@bence.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.28.1"
attrs = "^26.1.0"
pandas = "^3.0.5"
sqlite-diffable = "^0.6"
arrow = "^1.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
