[project]
name = "nvc-backlog"
version = "0.1.0"
description = ""
authors = [{ name = "Bence Nagy", email = "bence@underyx.me" }]
license = "MIT"
requires-python = ">=3.11"
dependencies = [
  "arrow>=1.4.0,<2",
  "requests>=2.34.2,<3",
  "types-requests>=2.33.0.20260712,<3",
]

[tool.ruff]
extend = "../../.ruff.toml"
