// Words people search the list pages with that are not in the data: what
// people call a USCIS form ("work permit", "green card"), and which country a
// consulate is in ("Mexico" finds Ciudad Juarez, where Mexico's immigrant
// visas are issued, as well as Mexico City). Hand-maintained here rather than
// in forms.json or the consulate tables, which the scrapers regenerate.

interface FormSearchTerms {
  /** A plain-language name, shown under the form's title, "Work permit
   * (EAD)"; null when the title says it already */
  aka: string | null;
  /** More words and phrases that find the form, not shown */
  keywords: string[];
}

/** Search terms per form number. Forms without an entry are found by their
 * number and title only. */
export const FORM_SEARCH_TERMS: Record<string, FormSearchTerms> = {
  "I-130": {
    aka: "Family petition: spouse, child, parent or sibling",
    keywords: [
      "husband",
      "wife",
      "marriage",
      "relative",
      "green card",
      "IR1",
      "CR1",
      "F2A",
    ],
  },
  "I-129F": {
    aka: "Fiancé(e) petition (K-1 visa)",
    keywords: ["fiance", "fiancee", "K1", "K3", "K visa"],
  },
  "I-485": {
    aka: "Green card from inside the US (adjustment of status)",
    keywords: ["AOS", "permanent resident"],
  },
  "I-765": {
    aka: "Work permit (EAD)",
    keywords: ["employment authorization document"],
  },
  "I-131": {
    aka: "Advance parole, reentry permit and other travel documents",
    keywords: ["travel document", "parole in place"],
  },
  "I-751": {
    aka: "Removing conditions on a 2-year green card",
    keywords: ["conditional green card", "10 year green card"],
  },
  "I-90": {
    aka: "Renewing or replacing a green card",
    keywords: ["renew", "replace", "lost", "expired"],
  },
  "N-400": {
    aka: "Citizenship (naturalization)",
    keywords: ["naturalize", "citizen"],
  },
  "N-600": { aka: null, keywords: ["child born abroad"] },
  "N-565": { aka: null, keywords: ["lost certificate", "replace certificate"] },
  "N-648": {
    aka: "Disability exception for the citizenship test",
    keywords: ["citizenship test", "naturalization test"],
  },
  "I-140": {
    aka: "Employment-based green card petition (EB-1, EB-2, EB-3)",
    keywords: ["EB1", "EB2", "EB3", "NIW", "national interest waiver", "PERM"],
  },
  "I-129": {
    aka: "Work visa petition (H-1B, L-1, O-1 and others)",
    keywords: ["H1B", "L1", "O1", "work visa"],
  },
  "I-539": {
    aka: "Extending or changing a visitor, student or other stay",
    keywords: [
      "extend stay",
      "change status",
      "B2",
      "visitor",
      "F1",
      "student",
    ],
  },
  "I-821D": { aka: "DACA", keywords: ["dreamers", "deferred action"] },
  "I-821": { aka: "TPS", keywords: ["temporary protected status"] },
  "I-589": { aka: null, keywords: ["asylee"] },
  "I-730": {
    aka: "Follow-to-join for relatives of refugees and asylees",
    keywords: ["follow to join"],
  },
  "I-601A": {
    aka: "Provisional unlawful presence waiver",
    keywords: ["waiver", "3 year bar", "10 year bar"],
  },
  "I-526": { aka: "EB-5 investor petition", keywords: ["EB5", "investor"] },
  "I-526E": { aka: "EB-5 investor petition", keywords: ["EB5", "investor"] },
  "I-829": {
    aka: "EB-5 investor: removing conditions",
    keywords: ["EB5", "conditional green card"],
  },
  "I-956": { aka: null, keywords: ["EB5"] },
  "I-956F": { aka: null, keywords: ["EB5"] },
  "I-956G": { aka: null, keywords: ["EB5"] },
  "I-956H": { aka: null, keywords: ["EB5"] },
  "I-956K": { aka: null, keywords: ["EB5"] },
  "I-924": { aka: null, keywords: ["EB5"] },
  "I-360": {
    aka: "VAWA, widow(er), special immigrant juvenile, religious worker and others",
    keywords: ["SIJ"],
  },
  "I-918": { aka: "U visa", keywords: ["crime victim"] },
  "I-914": { aka: "T visa", keywords: ["human trafficking"] },
  "I-290B": {
    aka: null,
    keywords: ["appeal", "reopen", "reconsider", "denial"],
  },
  "I-102": { aka: "Replacing an I-94 record", keywords: ["I94"] },
  "I-600": { aka: null, keywords: ["adoption"] },
  "I-800": { aka: null, keywords: ["adoption", "orphan"] },
  "I-881": { aka: "NACARA", keywords: ["cancellation of removal"] },
  "I-941": { aka: null, keywords: ["startup", "founder"] },
};

/** The country of each post in the consulate data, by post slug, with other
 * names people search for in parentheses. The consulate list shows it and
 * searches it; its build fails on a post that is missing here
 * (checkPostCountries), so a new post gets noticed. */
export const POST_COUNTRIES: Record<string, string> = {
  abidjan: "Côte d'Ivoire (Ivory Coast)",
  "abu-dhabi": "United Arab Emirates (UAE)",
  abuja: "Nigeria",
  accra: "Ghana",
  "addis-ababa": "Ethiopia",
  algiers: "Algeria",
  almaty: "Kazakhstan",
  amman: "Jordan",
  amsterdam: "Netherlands",
  ankara: "Turkey (Türkiye)",
  antananarivo: "Madagascar",
  apia: "Samoa",
  ashgabat: "Turkmenistan",
  asmara: "Eritrea",
  astana: "Kazakhstan",
  asuncion: "Paraguay",
  athens: "Greece",
  auckland: "New Zealand",
  baghdad: "Iraq",
  baku: "Azerbaijan",
  bamako: "Mali",
  "bandar-seri-begawan": "Brunei",
  bangkok: "Thailand",
  banjul: "Gambia",
  beijing: "China",
  beirut: "Lebanon",
  belfast: "United Kingdom (UK, Northern Ireland)",
  belgrade: "Serbia",
  belmopan: "Belize",
  berlin: "Germany",
  bern: "Switzerland",
  bishkek: "Kyrgyzstan",
  bogota: "Colombia",
  brasilia: "Brazil",
  bratislava: "Slovakia",
  brazzaville: "Republic of the Congo",
  bridgetown: "Barbados",
  brussels: "Belgium",
  bucharest: "Romania",
  budapest: "Hungary",
  "buenos-aires": "Argentina",
  bujumbura: "Burundi",
  cairo: "Egypt",
  calgary: "Canada",
  "cape-town": "South Africa",
  caracas: "Venezuela",
  casablanca: "Morocco",
  chengdu: "China",
  chennai: "India",
  "chiang-mai": "Thailand",
  chisinau: "Moldova",
  "ciudad-juarez": "Mexico",
  colombo: "Sri Lanka",
  conakry: "Guinea",
  copenhagen: "Denmark",
  cotonou: "Benin",
  curacao: "Curaçao",
  dakar: "Senegal",
  "dar-es-salaam": "Tanzania",
  department: "United States",
  dhahran: "Saudi Arabia",
  dhaka: "Bangladesh",
  dili: "Timor-Leste (East Timor)",
  djibouti: "Djibouti",
  doha: "Qatar",
  dubai: "United Arab Emirates (UAE)",
  dublin: "Ireland",
  durban: "South Africa",
  dushanbe: "Tajikistan",
  erbil: "Iraq",
  florence: "Italy",
  frankfurt: "Germany",
  freetown: "Sierra Leone",
  gaborone: "Botswana",
  georgetown: "Guyana",
  guadalajara: "Mexico",
  guangzhou: "China",
  "guatemala-city": "Guatemala",
  guayaquil: "Ecuador",
  halifax: "Canada",
  hamilton: "Bermuda",
  hanoi: "Vietnam",
  harare: "Zimbabwe",
  havana: "Cuba",
  helsinki: "Finland",
  hermosillo: "Mexico",
  "ho-chi-minh-city": "Vietnam",
  "hong-kong": "Hong Kong and Macau",
  hyderabad: "India",
  islamabad: "Pakistan",
  istanbul: "Turkey (Türkiye)",
  jakarta: "Indonesia",
  jeddah: "Saudi Arabia",
  jerusalem: "Israel, the West Bank and Gaza",
  johannesburg: "South Africa",
  juba: "South Sudan",
  kabul: "Afghanistan",
  kampala: "Uganda",
  karachi: "Pakistan",
  kathmandu: "Nepal",
  khartoum: "Sudan",
  kigali: "Rwanda",
  kingston: "Jamaica",
  kinshasa: "Democratic Republic of the Congo (DRC)",
  kolkata: "India",
  kolonia: "Micronesia",
  koror: "Palau",
  krakow: "Poland",
  "kuala-lumpur": "Malaysia",
  "kuwait-city": "Kuwait",
  kyiv: "Ukraine",
  "la-paz": "Bolivia",
  lagos: "Nigeria",
  libreville: "Gabon",
  lilongwe: "Malawi",
  lima: "Peru",
  lisbon: "Portugal",
  ljubljana: "Slovenia",
  lome: "Togo",
  london: "United Kingdom (UK, England, Britain)",
  luanda: "Angola",
  lusaka: "Zambia",
  luxembourg: "Luxembourg",
  madrid: "Spain",
  majuro: "Marshall Islands",
  malabo: "Equatorial Guinea",
  managua: "Nicaragua",
  manama: "Bahrain",
  manila: "Philippines",
  maputo: "Mozambique",
  maseru: "Lesotho",
  matamoros: "Mexico",
  mbabane: "Eswatini (Swaziland)",
  melbourne: "Australia",
  merida: "Mexico",
  "mexico-city": "Mexico",
  milan: "Italy",
  minsk: "Belarus",
  monrovia: "Liberia",
  monterrey: "Mexico",
  montevideo: "Uruguay",
  montreal: "Canada",
  moscow: "Russia",
  mumbai: "India",
  munich: "Germany",
  muscat: "Oman",
  naha: "Japan (Okinawa)",
  nairobi: "Kenya",
  naples: "Italy",
  nassau: "Bahamas",
  ndjamena: "Chad",
  "new-delhi": "India",
  niamey: "Niger",
  nicosia: "Cyprus",
  nogales: "Mexico",
  nouakchott: "Mauritania",
  "nuevo-laredo": "Mexico",
  osakakobe: "Japan",
  oslo: "Norway",
  ottawa: "Canada",
  ouagadougou: "Burkina Faso",
  "panama-city": "Panama",
  paramaribo: "Suriname",
  paris: "France",
  perth: "Australia",
  "phnom-penh": "Cambodia",
  podgorica: "Montenegro",
  "port-au-prince": "Haiti",
  "port-louis": "Mauritius",
  "port-moresby": "Papua New Guinea",
  "port-of-spain": "Trinidad and Tobago",
  "porto-alegre": "Brazil",
  prague: "Czech Republic (Czechia)",
  praia: "Cabo Verde (Cape Verde)",
  pristina: "Kosovo",
  quebec: "Canada",
  quito: "Ecuador",
  rangoon: "Burma (Myanmar)",
  recife: "Brazil",
  reykjavik: "Iceland",
  riga: "Latvia",
  "rio-de-janeiro": "Brazil",
  riyadh: "Saudi Arabia",
  rome: "Italy",
  "san-jose": "Costa Rica",
  "san-salvador": "El Salvador",
  santiago: "Chile",
  "santo-domingo": "Dominican Republic",
  "sao-paulo": "Brazil",
  sarajevo: "Bosnia and Herzegovina",
  seoul: "South Korea",
  shanghai: "China",
  shenyang: "China",
  singapore: "Singapore",
  skopje: "North Macedonia",
  sofia: "Bulgaria",
  "st-petersburg": "Russia",
  stockholm: "Sweden",
  surabaya: "Indonesia",
  suva: "Fiji",
  sydney: "Australia",
  taipei: "Taiwan",
  tallinn: "Estonia",
  tashkent: "Uzbekistan",
  tbilisi: "Georgia",
  tegucigalpa: "Honduras",
  "tel-aviv": "Israel",
  tijuana: "Mexico",
  tirana: "Albania",
  tokyo: "Japan",
  toronto: "Canada",
  tunis: "Tunisia",
  ulaanbaatar: "Mongolia",
  "us---domestic": "United States",
  valletta: "Malta",
  vancouver: "Canada",
  vienna: "Austria",
  vientiane: "Laos",
  vilnius: "Lithuania",
  vladivostok: "Russia",
  warsaw: "Poland",
  windhoek: "Namibia",
  wuhan: "China",
  yaounde: "Cameroon",
  yekaterinburg: "Russia",
  yerevan: "Armenia",
  zagreb: "Croatia",
};

/** Fails the build when a post in the data has no country in POST_COUNTRIES,
 * so that a post State adds gets one. */
export function checkPostCountries(postSlugs: string[]): void {
  const missing = postSlugs.filter((slug) => !(slug in POST_COUNTRIES));
  if (missing.length > 0)
    throw new Error(
      `api/searchTerms.ts: POST_COUNTRIES has no country for ${missing.join(
        ", ",
      )}`,
    );
}
